services:
  - type: web
    name: earnings-gap-apps
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn apps.multi:server --chdir .
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
